name: 'ğŸ‘·â€â™‚ï¸ Build'

on:
  push:
    branches:
      - marfeel-master

jobs:
  install:
    runs-on: ubuntu-latest
    name: ğŸ“¦ Install cache
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # ğŸ‘ˆ Required to retrieve git history

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 'Cache dependencies'
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            modules-

      - name: 'Install dependencies'
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

  build-and-publish:
    runs-on: ubuntu-latest
    name: 'ğŸ›  Build and Publish ğŸš€ '
    needs: [install]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # ğŸ‘ˆ Required to retrieve git history

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 'Cache dependencies'
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: 'ğŸ›  Build'
        run: npm run prepare-release

      - name: 'Move to Marfeel Lexical'
        run: cd ./packages/lexical-marfeel/npm

      - name: 'ğŸš€ Publish'
        uses: Marfeel/github-actions/common/actions/publish@master
        if: github.event_name == 'push' && github.ref == 'refs/heads/marfeel-master'
        with:
          nexus-token: ${{ secrets.NPM_NEXUS_AUTH }}
          build-number: ${{ github.run_id }}
