name: 'ğŸ‘·â€â™‚ï¸ Build'

on:
  push:
    branches:
      - marfeel-master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # ğŸ‘ˆ Required to retrieve git history

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: ğŸ“¦ Initialize
        run: npm ci

      - name: ğŸ§¹ Lint
        run: npm run flow

      - name: âœ… Tests
        run: npm run test-unit

      - name: ğŸ›  Build
        run: npm run prepare-release

      - name: 'ğŸš€ Publish'
        uses: Marfeel/github-actions/common/actions/publish@master
        if: github.event_name == 'push' && github.ref == 'refs/heads/marfeel-master'
        working-directory: ./packages/lexical-marfeel/npm
        with:
          nexus-token: ${{ secrets.NPM_NEXUS_AUTH }}
          build-number: ${{ github.run_id }}
